export const TRANSACTION_SAVE = 'TRANSACTION_SAVE';
export const TRANSACTION_SAVE_REQUEST = 'TRANSACTION_SAVE_REQUEST';
export const TRANSACTION_SAVE_SUCCESS = 'TRANSACTION_SAVE_SUCCESS';
export const TRANSACTION_SAVE_FAIL = 'TRANSACTION_SAVE_FAIL';

export const TRANSACTION_DELETE = 'TRANSACTION_DELETE';
export const TRANSACTION_DELETE_REQUEST = 'TRANSACTION_DELETE_REQUEST';
export const TRANSACTION_DELETE_SUCCESS = 'TRANSACTION_DELETE_SUCCESS';
export const TRANSACTION_DELETE_FAIL = 'TRANSACTION_DELETE_FAIL';
