export const TRANSACTIONS_REQUEST = 'TRANSACTIONS_REQUEST';
export const TRANSACTIONS_SUCCESS = 'TRANSACTIONS_SUCCESS';
export const TRANSACTIONS_FAIL = 'TRANSACTIONS_FAIL';

export const TRANSACTION_ADD = 'TRANSACTION_ADD';
export const TRANSACTION_DELETE = 'TRANSACTION_DELETE';
